### ISSUE TITLE
Incorrect naming in settings

### ISSUE THREAD

**Issue by weyh** [Mr0nline/React-Import-Sorter#5]
In settings under `Extensions` tab the extension is called `My Extension`.
![image](https://github.com/Mr0nline/React-Import-Sorter/assets/16374863/4f66cd91-75d0-472d-8f95-6348f6859079)

**Comment by Mr0nline** [comment]
@weyh thanks for reporting. Will take a look and update it in shortwhile! 👍

**Comment by Mr0nline** [comment]
@weyh Fixed in `v0.0.7`
